.circleci/config.yml
.dockerignore
.gitignore
.pylintrc
CHANGELOG.md
Dockerfile
MANIFEST.in
Makefile
bin/compose
bin/pylint
bin/pytest
bin/ralph
docker-compose.yml
setup.cfg
setup.py
src/ralph/__main__.py
src/ralph/exceptions.py
src/ralph/filters.py
src/ralph/parsers.py
tests/conftest.py
tests/fixtures/logs.py
tests/test_filters.py
tests/test_parsers.py

This first work is the first step of a POC of what will be openfun/ralph.

[POC] Add openedx tracking logs parsing

---

README.md

Our project is no longer edx-specific, we are more generic than that!

📝(readme) improve project title

---

CHANGELOG.md
src/ralph/backends/mixins.py
src/ralph/backends/storage/base.py
src/ralph/backends/storage/fs.py
src/ralph/backends/storage/ldp.py
src/ralph/cli.py
src/ralph/defaults.py
tests/backends/storage/test_base.py
tests/backends/storage/test_fs.py
tests/test_cli.py

The purpose of ralph is to be able to store archives in many formats, and the filesystem one was lacking.
Related to #16

Add file system storage and push command

---

.circleci/config.yml
.dockerignore
.env.dist
.gitignore
CHANGELOG.md
Dockerfile
Makefile
README.md
arnold.yml
docker-compose.yml
setup.cfg
src/ralph/backends/database/es.py
src/ralph/cli.py
src/tray/templates/services/app/cronjob_pipeline.yml.j2
src/tray/templates/services/app/dc.yml.j2
src/tray/templates/services/app/secret.yml.j2
src/tray/templates/volumes/history.yml.j2
src/tray/tray.yml
src/tray/vars/all/main.yml
src/tray/vars/settings.yml
src/tray/vars/vault/main.yml.j2
tests/test_cli.py

Now that Ralph is almost ready, we need to be able to deploy it to k8s with our beloved Arnold tool.
Fix #18

Add Arnold tray

---

CHANGELOG.md
setup.cfg

- Implement base CLI commands (list, extract, fetch & push) for supported backends
- Support for ElasticSearch database backend
- Support for LDP storage backend
- Support for FS storage backend
- Parse (gzipped) tracking logs in GELF format
- Support for application's configuration file
- Add optional sentry integration
- Distribute Arnold's tray to deploy Ralph in a k8s cluster as cronjobs

🔖(major) first major release 1.0.0

---

.circleci/config.yml

YAML anchors misuse leads to drop the docker login step, so we are not able to publish images to DockerHub.

💚(circle) fix docker login step

---

CHANGELOG.md
setup.cfg
src/ralph/cli.py
src/ralph/utils.py
tests/test_cli.py

Ralph has a much more sophisticated logger setup and click_log
stopped functioning.
Remove click_log package dependency.

🔥(cli) remove click_log

---

.pylintrc
CHANGELOG.md
setup.cfg
src/ralph/backends/storage/ldp.py
src/ralph/cli.py
src/ralph/defaults.py
src/ralph/models/edx/base.py
src/ralph/models/edx/server.py
tests/backends/database/test_es.py
tests/backends/storage/test_fs.py
tests/backends/storage/test_ldp.py
tests/fixtures/edx/base.py
tests/fixtures/edx/server.py
tests/models/edx/test_base.py
tests/models/edx/test_server.py
tests/test_cli.py

The edx server events are the most simple and common events in the edx tracking logs. They are logged at almost all requests made to the edx lms. We want to validate them.

✨(models) add edx server event model

---

tests/backends/database/test_es.py
tests/backends/storage/test_base.py
tests/backends/storage/test_fs.py
tests/backends/storage/test_ldp.py
tests/backends/storage/test_swift.py
tests/backends/test_mixins.py
tests/fixtures/backends.py
tests/fixtures/edx/base.py
tests/fixtures/edx/browser.py
tests/fixtures/edx/server.py
tests/fixtures/logs.py
tests/models/edx/test_base.py
tests/models/edx/test_browser.py
tests/models/edx/test_server.py
tests/test_cli.py
tests/test_defaults.py
tests/test_filters.py
tests/test_logger.py
tests/test_parsers.py
tests/test_utils.py

Using the same convention for all tests improves readability.
Renaming the tests to make them more homogeneous.

✅(tests) rename tests

---

.circleci/config.yml
CHANGELOG.md
src/tray/templates/services/app/cronjob_pipeline.yml.j2
src/tray/templates/services/app/deploy.yml.j2
src/tray/templates/services/app/secret-es-ca.yml.j2
src/tray/templates/services/app/secret.yml.j2
src/tray/templates/volumes/history.yml.j2

Following recent work on migrating our apps to k8s [1], ralph was missing to the list!
References:
[1] https://github.com/openfun/arnold/pull/620

✨(tray) move to k8s

---

src/ralph/models/edx/__init__.py
src/ralph/models/edx/base.py
src/ralph/models/edx/browser.py
src/ralph/models/edx/converters/xapi/navigational.py
src/ralph/models/edx/converters/xapi/server.py
src/ralph/models/edx/enrollment/fields/contexts.py
src/ralph/models/edx/enrollment/fields/events.py
src/ralph/models/edx/enrollment/statements.py
src/ralph/models/edx/navigational/fields/events.py
src/ralph/models/edx/navigational/statements.py
src/ralph/models/edx/server.py
src/ralph/models/edx/textbook_interaction/statements.py
tests/models/edx/converters/xapi/test_navigational.py
tests/models/edx/converters/xapi/test_server.py
tests/models/edx/test_base.py
tests/models/edx/test_browser.py
tests/models/edx/test_enrollment.py
tests/models/edx/test_navigational.py
tests/models/edx/test_server.py
tests/models/test_converter.py
tests/models/test_selector.py
tests/models/test_validator.py
tests/test_cli.py

Based on the structure of xapi models implementation, the structure of edx models for already implemented events has been improved.

Restructure edx models code

---

.circleci/config.yml
.env.dist
CHANGELOG.md
Makefile
docker-compose.yml
setup.cfg
src/ralph/backends/database/es.py
src/ralph/backends/database/mongo.py
src/ralph/defaults.py
tests/backends/database/test_mongo.py
tests/conftest.py
tests/fixtures/backends.py
tests/test_cli.py

MongoDB is a classical database for LRSs such as LearningLocker or Apereo Learning Analytics Initiative. Supporting this backend seems a must-have for Ralph.

Add MongoDB backend

---

README.md
docs/index.md

Ralph is a complex objects: as a toolbox, it can be used in various ways. The project's documentation does not reflect possible usages.
Better describe core features and installation schemes.

📝(project) improve project description and quick start guide

---

.circleci/config.yml
CHANGELOG.md
Dockerfile
docs/index.md
setup.cfg
src/ralph/models/xapi/fields/common.py

Python 3.11 is the most recent python stable release. We should support it.

⬆️(project) upgrade base python version to 3.11

---

docs/api.md
docs/index.md

Update documentation and fix some issues.

📝(project) correct minor issue in documentation

---

.circleci/config.yml
.pylintrc
src/ralph/api/auth.py
src/ralph/api/forwarding.py
src/ralph/api/routers/statements.py
src/ralph/backends/database/base.py
src/ralph/backends/database/es.py
src/ralph/backends/database/mongo.py
src/ralph/backends/storage/swift.py
src/ralph/cli.py
src/ralph/models/converter.py
tests/api/test_statements_post.py
tests/backends/database/test_es.py
tests/backends/storage/test_fs.py
tests/backends/storage/test_ldp.py
tests/backends/storage/test_s3.py
tests/backends/storage/test_swift.py
tests/backends/test_mixins.py
tests/conftest.py
tests/fixtures/backends.py
tests/fixtures/hypothesis_strategies.py
tests/models/edx/converters/xapi/test_server.py
tests/models/xapi/test_navigation.py
tests/models/xapi/test_video.py

We want to make sure that Ralph is compatible with python 3.9, 3.10, and 3.11.

👷(circle) run tests with multiple python versions in the CI

---

README.md

We have a community now! People are looking for ways to interact.

🧑‍💻(project) add Discord server link

---

CHANGELOG.md
src/ralph/models/xapi/__init__.py
src/ralph/models/xapi/concepts/verbs/tincan_vocabulary.py
src/ralph/models/xapi/video/contexts.py
src/ralph/models/xapi/video/statements.py
tests/models/xapi/concepts/test_verbs.py
tests/models/xapi/test_video.py

Simply add the http://id.tincanapi.com/verb/downloaded to the tincan vocabulary so it can be used by other projects (here warren)
Add the `DownloadedVerb` as a new `BaseXapiVerb`
closes #367

✨(models) add downloaded verb to tincan vocabulary

---

src/ralph/backends/data/ldp.py
tests/backends/data/test_ldp.py
tests/conftest.py
tests/fixtures/backends.py

Storage and Database backends have similar interfaces and usage.
Unify the interfaces of database and storage backends into a single DataBackend interface.

🏗️(backends) unify data backends ldp

---

CHANGELOG.md
src/helm/ralph/Chart.yaml
src/helm/ralph/templates/deployment.yaml
src/helm/ralph/templates/hpa.yaml
src/helm/ralph/templates/ingress.yaml
src/helm/ralph/templates/pvc.yml
src/helm/ralph/templates/service.yaml
src/helm/ralph/values.yaml

296 helm feedback

---

src/ralph/backends/data/fs.py
src/ralph/backends/lrs/base.py
src/ralph/backends/lrs/fs.py
tests/backends/data/test_base.py
tests/backends/lrs/test_fs.py
tests/conftest.py
tests/fixtures/backends.py

We want to provide an LRS backend that could be added to Ralph's LRS without additional dependencies.
Note: depends on changes from #336

🏗️(backends) unify data backends fs lrs

---

setup.cfg
src/ralph/backends/data/async_es.py
src/ralph/backends/data/base.py
src/ralph/backends/lrs/async_es.py
src/ralph/backends/lrs/base.py
src/ralph/backends/lrs/es.py
src/ralph/utils.py
tests/backends/data/test_async_es.py
tests/backends/lrs/test_async_es.py
tests/conftest.py
tests/fixtures/backends.py

Add an asynchronous Elasticsearch backend to speed up queries and bulk inserts.

✨(backends) add async elasticsearch data backend

---

.circleci/config.yml

Ensure renovate configuration file is valid.
Add a CI job which uses renovate CLI dependency tool to validate configurations.

👷(project) ensure renovate configuration file is valid

---

CHANGELOG.md
src/ralph/api/routers/statements.py
src/ralph/backends/database/clickhouse.py
src/ralph/backends/database/es.py
src/ralph/backends/database/mongo.py
src/ralph/backends/http/async_lrs.py

Ensures PEP8 compliance without disabling PyLint.
Implemented camel case aliases on attributes or routes' parameters. Let me know if I am being too pedantic, and this breaking change is not worth it.

🎨(api) convert camelCase variables to snake_case 

---

.circleci/config.yml
README.md

- README should emphasize that Ralph is an LRS along with a CLI and library.
- README should point quickly to the documentation.
- Adding Ralph logo as it would be a nice eye-catcher.
- Adding shields for Tests, PyPi package, python versions supported and Docker image version.
~~- Adding a Contributors section to thank every contributor.~~

📝(project) improve README

---

src/ralph/cli.py
tests/test_cli.py

The `backends_options` function eagerly imports all backends to construct their options for each command that uses backend options, regardless of which CLI command is invoked (even when the cli module is just imported).
This is not very efficient.
Also, currently, CLI logging is configured after backend discovery, which does not allow controlling the logging levels used during backend discovery.

⚡️(cli) lazy backend options

---

src/helm/ralph/Chart.yaml

We need recent Helm chart changes to deploy Ralph along with Warren.
Manually publish a new chart release with recent changes.

🔖(helm) bump chart release to 0.2.0

---

CHANGELOG.md
src/helm/CHANGELOG.md

Changes on Ralph Helm chart are decorrelated from Ralph changes.
Creating a separated helm chart CHANGELOG to keep track of these changes.

📝(project) add a specific CHANGELOG.md for the helm chart

---

src/ralph/api/routers/health.py

Inspired from Warren #144, we can use a custom model for heartbeat response.
Adding `Heartbeat` pydantic model for status.

🎨(api) improve heartbeat endpoint

---

docs/index.md
docs/tutorials/development_guide.md
mkdocs.yml

Following @lebaudantoine review of our documentation, improving main documentation page and developer guide.

📝(project) improve main doc page and developer guide

---

docs/contribute.md
docs/index.md
docs/tutorials/development_guide.md

Following @SergioSim remarks on PR #535, improving some parts of the documentation.

📝(project) improve documentation readability

---

CHANGELOG.md
UPGRADE.md
src/ralph/backends/data/swift.py
tests/backends/data/test_swift.py

We want to keep our changelog and upgrade guide up to date with the latest changes made to Ralph's backends.

📝(project) update ralph v4 upgrade guide and changelog

---

src/ralph/__init__.py

Beta pre-release to test both PyPi package and docker image before stable release.
Install Python package with:
`pip install --pre ralph-malph`
- Backends: Add `Writable` and `Listable` interfaces to distinguish supported
functionalities among `data` backends
- Backends: Add `max_statements` option to data backends `read` method
- Backends: Add `prefetch` option to async data backends `read` method
- Backends: Add `concurrency` option to async data backends `write` method
- Backends: Add `get_backends` function to automatically discover backends
for CLI and LRS usage
- Backends: Add client options for WSDataBackend
- Backends: Add `READ_CHUNK_SIZE` and `WRITE_CHUNK_SIZE` data backend settings
- Models: Implement Pydantic model for LRS Statements resource query parameters
- Models: …

🔖(prerelease) bump release to 4.0.0-beta1

---

src/helm/CHANGELOG.md
src/helm/ralph/Chart.yaml

Added
- A NOTE.txt file with instructions for chart users
- A ConfigMap template for Ralph configuration
- A ConfigMap for logging configuration
- A secret Manifest for helping user configure Ralph
- A Helm connection test for Ralph
Changed
- Upgrade appVersion to `4.0.0`
- Environment variables are now provided through a ConfigMap and a Secret
- Improve Ingress configuration
- Improved values based on Helm chart template file
Removed
- Dependencies to mongodb and clickhouse (managed outside of chart scope)
- Secrets template and vault values (managed outside of chart scope)

🔖(helm) bump release to 0.3.0

---

.circleci/config.yml

Several problems with the helm publication job:

💚(helm) fix helm publication job

---

src/helm/CHANGELOG.md
src/helm/ralph/Chart.yaml

- Upgrade appVersion to `4.1.0`

🔖(helm) bump release to 0.4.0

---

Makefile
docker-compose.yml

Fix bugs noticed on developer machine

Fix dev bugs

---

src/helm/CHANGELOG.md
src/helm/ralph/Chart.yaml

- Upgrade appVersion to `5.0.1`

🔖(helm) bump release to 0.5.1

---

src/swarm/README.md
src/swarm/auth/auth.json
src/swarm/docker-compose.prod.yml
src/swarm/env.d/logging-config.yaml
src/swarm/env.d/ralph.env

This commit adds a docker compose swarm file to deploy Ralph, along with instructions to do so.

📝(swarm) add documentation to deploy ralph with docker swarm

---

Dockerfile

Since a recent version of Docker, many warnings are raised at build time from the Dockerfile.
Fixing them.

🚨(project) resolve dockerfile build warnings
