openfun/ralph

- .circleci/config.yml
Docker will soon add a rate limit on image pulls from DockerHub. This rate limit is based on the request IP for anonymous users; in a CI context, CircleCI IPs will be taken into account, hence quota will be reached quickly.
To prevent this behavior, we should authenticate to DockerHub before pulling or building images so that this rate limit is now on a per-user basis.
Hat tip to @lunika for this copy/pasta from previous implementation he did on other projects.
> 👷(circle) authenticate to pull images from DockerHub

- .dockerignore
- .env.dist
- .gitignore
- CHANGELOG.md
- Dockerfile
- Makefile
- README.md
- bin/pylint
- bin/pytest
- bin/ralph
- docker-compose.yml
- setup.cfg
- src/ralph/__main__.py
- src/ralph/backends/mixins.py
- src/ralph/backends/storage/__init__.py
- src/ralph/backends/storage/base.py
- src/ralph/backends/storage/ldp.py
- src/ralph/cli.py
- src/ralph/defaults.py
- src/ralph/exceptions.py
- src/ralph/parsers.py
- src/ralph/utils.py
- tests/backends/storage/test_base.py
- tests/backends/storage/test_ldp.py
- tests/backends/test_mixins.py
- tests/fixtures/backends.py
- tests/test_cli.py
- tests/test_parsers.py
- tests/test_utils.py
We need to automate fetching new LDP-stored events and push them to our ES instance. To achieve this, `ralph` should be used as a stream-based CLI that can pull / convert / push learning events from a storage backend to a database backend.
Current work mostly focuses on defining a shared architecture for parsers, storage backends and CLI commands. An example usage follows:
```
$ ralph list -b ldp
ARCHIVE_ID_01
ARCHIVE_ID_02
ARCHIVE_ID_03
ARCHIVE_ID_04
ARCHIVE_ID_05
$ ralph fetch -b ldp ARCHIVE_ID_02 | gunzip | ralph extract -p gelf
{
... event ...
}
```
> Add LDP backend and base CLI

- setup.cfg
- tests/fixtures/logs.py
Djehouty is a legacy library theoretically only compatible with python2. Hat tip to @pyup-bot 
Djehouty has been rewritten by the OVH team to be fully compatible with python3. Let's switch to it even if we only use the GELF formatter for testing.
> ⬆️(project) move to a python3 compatible GELF library

- .circleci/config.yml
- .env.dist
- CHANGELOG.md
- Makefile
- bin/es
- docker-compose.yml
- setup.cfg
- src/ralph/backends/__init__.py
- src/ralph/backends/database/__init__.py
- src/ralph/backends/database/base.py
- src/ralph/backends/database/es.py
- src/ralph/backends/storage/__init__.py
- src/ralph/cli.py
- src/ralph/defaults.py
- src/ralph/exceptions.py
- src/ralph/utils.py
- tests/backends/database/test_es.py
- tests/conftest.py
- tests/fixtures/backends.py
- tests/test_cli.py
- tests/test_utils.py
Ralph should be able to publish or get statements from database backends; our first implementation of such support should be Elasticsearch since its used in production to mine collected xAPI statements.
Fix #16 
Fix #17
> ✨(backends) add Elasticsearch database backend

- bin/ralph
Some ralph commands do not require additional docker dependencies
Example: extract command or push -b fs command
Also, when docker-compose loads additional dependencies it writes to the standard output, which inferences ralph commands reading from the standard output.
Example: stream | ralph extract ... | read output
```
Starting ralph_elasticsearch_1 ... done
extracted stream
```
> Add --no-deps argument to ralph

- .circleci/config.yml
- .gitignore
- CHANGELOG.md
- setup.cfg
- src/ralph/__init__.py
- src/ralph/cli.py
- src/ralph/defaults.py
- src/ralph/exceptions.py
- src/ralph/logger.py
- tests/test_defaults.py
- tests/test_logger.py
Ralph logs were quite simple and could not be configured
Using python's standard `logging` library, the logging can be customized from a configuration file, `defaults.py`
> Custom logging

- .circleci/config.yml
External contributions cannot inject secret environment variables in the CI execution context, leading some jobs to fail when a DockerHub login is required.
We should allow anonymous docker images pulling to mitigate the issue. It should work as long as CircleCI has an agreement with DockerHub to prevent bandwidth restrictions from their IPs.
> 💚(circle) allow docker hub anonymous mode

- CHANGELOG.md
- src/ralph/backends/database/base.py
- src/ralph/backends/database/es.py
- src/ralph/cli.py
- tests/backends/database/test_es.py
When bulk importing documents in ES, if a document is badly formatted (e.g. with mistyped fields), the bulk importation stops after the first chunk importation failure.
We now allow to force the importation regardless of indexation errors.
> ✨(cli) allow to force push for database backends

- CHANGELOG.md
- src/ralph/backends/database/es.py
- src/ralph/cli.py
- tests/backends/database/test_es.py
- tests/test_cli.py
The elasticsearch client supports various options to support a lot of connection scenarii with an elasticsearch cluster. Unfortunately current implementation of ralph is restricted to the `verify_certs` option only.
We now also support passing those options from the CLI using coma-separated key=value pairs:
```
$ ralph push --backend es --es-client-options ca_certs=/path/to/ca/certs,client_cert=/path/to/client/cert.pem
```
> ✨(backends:es) add support for supported client options

- CHANGELOG.md
- setup.cfg
- src/ralph/__init__.py
- Support for Swift storage backend
- Use the `push` command `--ignore-errors` option to ignore ES bulk import errors
- The elasticsearch backend now accepts passing all supported client options
- Remove click_log package dependency
- Upgrade pyyaml to 5.4.1
- Upgrade pandas to 1.2.1
> 🔖(minor) bump release to 1.1.0

- .env.dist
The environment variables are defined in `.env.dist` file and are commented. Users have to uncomment the definition line for running the application. 
The indication has been documented on the head of the file so that user are aware of doing it before running ralph.
> 📝(env) fix documentation of environment variables

- CHANGELOG.md
- src/ralph/models/edx/browser.py
- tests/fixtures/backends.py
- tests/fixtures/edx/browser.py
- tests/models/edx/test_browser.py
The edX page_close browser events are the most simple and common browser events in the edX tracking logs. We want to validate them.
> ✨(models) add edX page_close browser event model

- CHANGELOG.md
- setup.cfg
- src/ralph/filters.py
- src/ralph/parsers.py
- tests/test_filters.py
- tests/test_parsers.py
Pandas was introduced as a Ralph dependency for preliminary performance assessment and is now only used in the GELF parser. We think it's not worth it to have such dependency for a small use case.
The pandas dependancy have been completely removed and `json.loads()` is used instead of `dataframe` in the GELF parser.
`parsers` [code](https://github.com/SergioSim/ralph/blob/55b088b47ba0ccc1df1eae0102be6c6ba811ebe8/src/ralph/parsers.py) and [tests](https://github.com/SergioSim/ralph/blob/55b088b47ba0ccc1df1eae0102be6c6ba811ebe8/tests/test_parsers.py) have been readapted from commit `55b088b47ba0ccc1df1eae0102be6c6ba811ebe8`. 
`filters` [code](https://github.com/SergioSim/ralph/blob/55b088b47ba0ccc1df1eae0102be6c6ba811ebe8/src/ralph/filters.py) and …
> ➖(parsers) remove pandas dependency in GELF parser

- src/ralph/cli.py
- src/ralph/defaults.py
- src/ralph/exceptions.py
- src/ralph/filters.py
- src/ralph/logger.py
- tests/fixtures/backends.py
- tests/test_cli.py
- tests/test_defaults.py
- tests/test_logger.py
- tests/test_parsers.py
- tests/test_utils.py
The documentation of ralph is partially updated with docstrings. 
It has been noticed during review of PR #60. 
However, format of docstrings is not the same in each class or function. 
Some points are missing. 
To get a cleaner documentation, sentences format has been harmonized.
> ✏️(project) fix docstring typos for ralph documentation

- CHANGELOG.md
- src/tray/templates/services/app/cronjob_pipeline.yml.j2
- src/tray/templates/services/app/dc.yml.j2
- src/tray/templates/services/app/secret-es-ca.yml.j2
- src/tray/templates/services/app/secret.yml.j2
- src/tray/vars/all/main.yml
- src/tray/vars/vault/main.yml.j2
When requesting an elasticsearch cluster using self-generated CA certificates, the elasticsearch client is raising a warning message as it cannot verify the authenticity of SSL certificates.
To mitigate the issue, one need to copy the CA certificate in ralph's container and specify the CA certificate path for the "es" backend using the `--es-client-options ca_certs=/path/to/ca.pem` option.
If the `ES_CA_CERTIFICATE` is defined in ralph's vault, a dedicated secret will be generated and mounted in the following path `/usr/local/share/ca-certificates/es-cluster.pem` so that execution logs are not polluted with warning messages.
> ✨(tray) add support for ES cluster CA certs

- CHANGELOG.md
- setup.cfg
- src/ralph/__init__.py
- EdX server event pydantic model and factory
- EdX page_close browser event pydantic model and factory
- Tray: allow to specify a self-generated elasticsearch cluster CA certificate
- Tray: add missing Swift variables in the secret
- Tray: fix pods anti-affinity selector
- `pandas` is no longer required
> 🔖(minor) bump release to 1.2.0

- CHANGELOG.md
- src/tray/templates/services/app/dc.yml.j2
As Ralph is not a blue-green application, we cannot have a variable `version` field in the DC's label (it should be immutable).
Without this fix, one cannot deploy a new Ralph's release as k8s refuses to patch the object.
> 🐛(tray) remove version immutable field in selector

- CHANGELOG.md
- Dockerfile
In Docker images, the upgrades of system packages is not run when building. It represents a security failure, as we let failures of
previous packages versions in the images. 
We have added the `apt-get upgrade` command to ensure that packages are up-to-date with their latest version and security failures have been removed.
> 🔒(project) add system package upgrades in docker image builds

- mkdocs.yml
mk-docs based documentation proposes a color customization. By default, the primary color of the documentation is set to `indigo`.
> 📝(project) change documentation primary color

- CHANGELOG.md
- src/ralph/models/edx/__init__.py
- src/ralph/models/edx/base.py
- src/ralph/models/edx/browser.py
- src/ralph/models/edx/navigational.py
- src/ralph/models/edx/server.py
- src/ralph/models/selector.py
- tests/models/edx/test_browser.py
- tests/models/edx/test_navigational.py
- tests/models/test_selector.py
- tests/models/test_validator.py
- tests/test_cli.py
With the `validate` and `select` command newly implemented, it is now possible to implement edx tracking logs events pydantic models to validate incoming events in ralph. 
The first events implemented are the easiest (navigation).
> ✨(models) add edx navigational event pydantic models

- CHANGELOG.md
- src/ralph/models/edx/__init__.py
- src/ralph/models/edx/base.py
- src/ralph/models/edx/enrollment.py
- tests/models/edx/test_enrollment.py
edx enrollment events are common events in tracking logs and easy to represent. For the validation and selection commands of ralph, they are one of the easiest to modelise.
> ✨(models) add edx enrollment events pydantic models

- CHANGELOG.md
- src/tray/templates/services/app/deploy.yml.j2
A readiness probe for a pod that is not a server is useless. ~Moreover, ralph CLI's boot is too greedy, we need to reduce the liveness probe frequency to reduce useless CPU usage.~
Edit: as stated by @madmatah the same remark applies to the liveness probe.
Edit: we've decided to completely remove probes as they seems useless for a CLI.
> ⚡️(tray) adjust probes configuration

- CHANGELOG.md
- src/ralph/models/xapi/base.py
- src/ralph/models/xapi/config.py
- src/ralph/models/xapi/constants.py
- src/ralph/models/xapi/fields/actors.py
- src/ralph/models/xapi/fields/objects.py
- src/ralph/models/xapi/fields/verbs.py
- src/ralph/models/xapi/page_terminated.py
- src/ralph/models/xapi/page_viewed.py
- tests/models/xapi/fields/test_actors.py
- tests/models/xapi/fields/test_objects.py
- tests/models/xapi/fields/test_verbs.py
- tests/models/xapi/test_page_terminated.py
- tests/models/xapi/test_page_viewed.py
These pydantic models can be used for xAPI format validation.
The page_viewed pydantic model correspond to the edX `simple server event`.
The page_terminated pydantic model correspond to the edX `page_close browser event`.
> ✨(models) add xAPI page_viewed and page_terminated models

- CHANGELOG.md
- src/ralph/exceptions.py
- src/ralph/models/converter.py
- src/ralph/models/edx/converters/xapi/__init__.py
- src/ralph/models/edx/converters/xapi/base.py
- src/ralph/models/edx/converters/xapi/navigational.py
- src/ralph/models/edx/converters/xapi/server.py
- src/ralph/models/xapi/navigation/fields/objects.py
- src/ralph/utils.py
- tests/models/edx/converters/xapi/test_base.py
- tests/models/edx/converters/xapi/test_navigational.py
- tests/models/edx/converters/xapi/test_server.py
- tests/models/test_converter.py
- tests/test_utils.py
EdX server events are common events in the edX tracking logs.
We want to convert them to xAPI format.
`models/converter.py` defines the base converter.
`models/edx/converters/xapi/base.py` defines the base converter for edX to xAPI conversion.
`models/edx/converters/xapi/server.py` converts edX server events to xAPI format.
> ✨(models) add edX server event to xAPI converter

- docker-compose.yml
To integrate the elasticsearch service with other data-related tools, we use a dedicated bridged network called "potsie".
> 🔧(project) add potsie bridged network

- CHANGELOG.md
- src/ralph/backends/database/es.py
- tests/backends/database/test_es.py
- tests/test_cli.py
Elasticsearch supports multiple operation types (aka `op_type`s) for bulk action requests: create, index, delete and update.
Using Elasticsearch new index templates requires that you perform "create" operations instead of the default "index" operation. We need more flexibility in Ralph.
We now support all operation types that can be specified as a backend option in the CLI commands that allow the usage of the elasticsearch backend:
```
--es-op-type [create|index|update|delete]
```
> ✨(backends) add custom op_type support for es backend

- CHANGELOG.md
- setup.cfg
- src/ralph/__init__.py
- src/tray/tray.yml
- xAPI video `interacted` pydantic models
- xAPI video `terminated` pydantic models
- xAPI video `completed` pydantic models
- xAPI video `seeked` pydantic models
- xAPI video `initialized` pydantic models
- xAPI video `paused` pydantic models
- `convert` command to transform edx events to xAPI format
- EdX to xAPI converters for page `viewed` and`page_close` events
- Implement core event format converter
- xAPI video `played` pydantic models
- xAPI page `viewed` and page `terminated` pydantic models
- Implement edx navigational events pydantic models
- Implement edx enrollment events pydantic models
- Install security updates in project Docker images
- Model selector to retrieve associated pydantic model of a given event
- `validate` command to lint edx events using pydantic models
- …
> 🔖(major) bump release to 2.0.0

- CHANGELOG.md
- docker-compose.yml
- src/ralph/backends/database/es.py
- tests/backends/database/test_es.py
- tests/conftest.py
- tests/fixtures/backends.py
Pushing statements to an elasticsearch data stream fails due to index mapping inconsistency.
Removing the `"_type": "document"` to bulk actions seems to fix the issue.
Note that statements send to an elasticsearch data stream requires to name your timestamp field `@timestamp`.
> Fix elasticsearch datastream support

- CHANGELOG.md
- setup.cfg
- src/ralph/__init__.py
- src/tray/tray.yml
- Upgrade `elasticsearch` to `7.13.3`
- Restore elasticsearch backend datastream compatibility for bulk operations
> 🔖(patch) bump release to 2.0.1

- src/ralph/models/xapi/base.py
- tests/fixtures/logs.py
With the upgrade of pylint package, the stream handler requires to use a context.
It was ignored in the pull request #112 concerning the upgrade, and fix here, additionnally with yielding the logger.
> 🐛(fixture) fix context management for gelf logger fixture

- CHANGELOG.md
- Dockerfile
- setup.cfg
- src/ralph/backends/__init__.py
- src/ralph/backends/stream/__init__.py
- src/ralph/backends/stream/base.py
- src/ralph/backends/stream/ws.py
- src/ralph/cli.py
- src/ralph/defaults.py
- src/ralph/utils.py
- src/tray/templates/services/app/deploy.yml.j2
- src/tray/vars/all/main.yml
- tests/backends/stream/test_base.py
- tests/backends/stream/test_ws.py
- tests/conftest.py
- tests/fixtures/backends.py
- tests/test_cli.py
Some logging tools provide websockets for real-time processing. This is a great added-value for Ralph to support consuming such streams.
> Add websocket backend

- CHANGELOG.md
- src/ralph/models/edx/__init__.py
- src/ralph/models/edx/textbook_interaction/fields/events.py
- src/ralph/models/edx/textbook_interaction/statements.py
- tests/models/edx/test_textbook_interaction.py
Textbook interaction from `edx` comprises browser events emitted when the user navigates in chapters.
> ✨(models) add edx textbook interaction events pydantic models

- .circleci/config.yml
The arnold image used for the CI is outdated. It was not updated in the pull request related to this update (see #127)
change arnold image tag from `migration-to-k8s` to `master`
> Update arnold image tag for CI

- Makefile
All our project have a default `make run` rule to start the development stack. This project seems to be an exception.
Elasticsearch is used by Ralph itself, but also grafana in the potsie project using the potsie network. This service should be targetted by the default `run` Makefile rule.
> 🔧(project) add 'run' Makefile rule

- CHANGELOG.md
- src/ralph/models/edx/__init__.py
- src/ralph/models/edx/base.py
- src/ralph/models/edx/problem_interaction/fields/events.py
- src/ralph/models/edx/problem_interaction/statements.py
- src/ralph/models/edx/server.py
- tests/models/edx/problem_interaction/test_events.py
- tests/models/edx/problem_interaction/test_statements.py
Problem interaction events are `Edx` events generated during platform usage. They are emitted by the server or the browser to capture information about interactions with problems.
Write `pydantic` models, edge-case and selector tests for:
> Implement edx problem interaction events pydantic models

- CHANGELOG.md
- docker-compose.yml
Some fix about `elasticsearch` were necessary in the `docker-compose` file.
> Fix elasticsearch config

- bin/ralph
As we added the `ralph runserver` command, we added port bindings on `docker-compose run` through the `--service-ports` option. This caused issues when starting more than one `ralph` command (eg. for piping) because both processes attempted to bind the same port.
We can bind ports only when running the `ralph runserver` commands to avoid these conflicts.
Note: @jmaupetit I had to remove your logging additions as they broke piping JSON between `ralph` calls:
```
echo "Docker user: ${DOCKER_USER}"
echo "Extra options: ${RUN_EXTRA_OPTS[@]}"
```
> Fix port binding conflicts due to the new `runserver` command

- src/ralph/api/__init__.py
- src/ralph/api/auth.py
- tests/test_auth.py
As we built authentication into our Ralph API, we looked for auth middleware and found built-in, compatible middleware from Starlette that was explicitly compatible with FastAPI.
We did not know at that time that there are incompatibilities with this specific middleware that prevent us from doing any sort of authorization work with FastAPI, like this middleware does if used directly with Starlette.
See https://github.com/tiangolo/fastapi/issues/104
We moved on to refactor our authentication to use a FastAPI dependency instead of a middleware.
As we start actually using authorization scopes, we can build another layer of FastAPI dependency on top of our `authenticated_user` to require certain scopes to access a given resource.
> ♻️(api) rework authentication to use a fastapi dependency

- .circleci/config.yml
CircleCI will soon deprecate default base image for the machine executor.
We need to explicitly switch to the latest image stable release.
For more information about this migration please, refer to the migration guide:
https://circleci.com/docs/2.0/images/linux-vm/14.04-to-20.04-migration/
> 👷(circleci) migrate to machine image stable release

- CHANGELOG.md
- src/tray/templates/services/app/cronjob_pipeline.yml.j2
An empty ralph_cronjobs list generates an empty CronJobList template leading to a deployment failure, k8s refusing submitted manifest.
> 🐛(tray) do not create a cronjobs list when no cronjob has been defined

- CHANGELOG.md
- src/ralph/models/edx/__init__.py
- src/ralph/models/edx/video/fields/events.py
- src/ralph/models/edx/video/statements.py
- tests/models/edx/video/test_events.py
- tests/models/edx/video/test_statements.py
ralph could be useful for the openedx community as a conversion tool for edx generated learning logs. The video events specified by OpenEdx were not supported on ralph.
Add video events pydantic models from [events-routing-backends](https://github.com/openedx/event-routing-backends/blob/master/docs/event-mapping/Supported_events.rst#video-events)
> Add edx video pydantic models

- CHANGELOG.md
- src/ralph/backends/mixins.py
Mixins logger is not used for the history mixin, droping all messages to the root logger.
> 🐛(backends) fix history mixin logger

- .circleci/config.yml
- .dockerignore
- .gitignore
- .k3d-cluster.env.sh
- CHANGELOG.md
- Makefile
- docker-compose.yml
- docs/contribute.md
- src/ralph/api/__init__.py
- src/ralph/api/routers/health.py
- src/ralph/backends/database/base.py
- src/ralph/backends/database/es.py
- src/ralph/backends/database/mongo.py
- src/tray/templates/services/app/cronjob_pipeline.yml.j2
- src/tray/templates/services/app/deploy.yml.j2
- src/tray/templates/services/app/ingress.yml.j2
- src/tray/templates/services/app/secret-lrs-auth.yml.j2
- src/tray/templates/services/app/static-svc.yml.j2
- src/tray/templates/services/app/svc.yml.j2
- src/tray/vars/all/main.yml
- src/tray/vars/settings.yml
- src/tray/vars/vault/main.yml.j2
- tests/api/test_health.py
- tests/backends/database/test_es.py
- tests/backends/database/test_mongo.py
Add support to run Ralph's LRS server on k8s.
> Tray: add LRS server

- .circleci/config.yml
- CHANGELOG.md
- Dockerfile
- docs/index.md
- setup.cfg
- src/ralph/conf.py
Ralph can be used as a CLI, as a server, or as a library. To handle this complexity, we need to split dependencies.
We decided to split dependencies to core and extra requirements:
- the core package only contains dependencies to use Ralph as a library (mostly to use models in a python project),
- the `cli` extra installs Click-related dependencies,
- the `backends` extra installs all supported backends; it might also correspond to a library usage,
- the `lrs` extra installs FastAPI-related dependencies for the LRS server implementation.
A full installation command would look like:
```
pip install ralph-malph[backends,cli,lrs]
```
While a library installation could be:
```
pip install ralph-malph
```
or
```
pip install ralph-malph[backends]
```
Depends on #217 for the Tray testing in the …
> 📦️(project) improve dependencies management

- CHANGELOG.md
- setup.cfg
- src/ralph/__init__.py
- src/tray/tray.yml
- Implement edx video browser events pydantic models
- Create a `post` endpoint for statements implementing the LRS spec
- Implement support for the MongoDB database backend
- Implement support for custom queries when using database backends `get` method (used in the `fetch` command)
- Add dotenv configuration file support and `python-dotenv` dependency
- Add `host` and `port` options for the `runserver` cli command
- Add support for database selection when running the Ralph LRS server
- Implement support for xAPI statement forwarding
- Add database backends `status` checking
- Add `health` LRS router
- Tray: add LRS server support
- Migrate to `python-legacy` handler for `mkdocstrings` package
- Upgrade `click` to `8.1.3`
- Upgrade `elasticsearch` to `8.3.3`
- Upgrade `fastapi` to …
> 🔖(major) bump release to 3.0.0

- CHANGELOG.md
- bin/es
- src/ralph/exceptions.py
- src/ralph/models/converter.py
- src/ralph/models/selector.py
- src/ralph/models/validator.py
- tests/models/edx/problem_interaction/test_statements.py
- tests/models/edx/test_enrollment.py
- tests/models/edx/test_navigational.py
- tests/models/edx/test_server.py
- tests/models/edx/test_textbook_interaction.py
- tests/models/edx/video/test_statements.py
- tests/models/test_selector.py
- tests/models/test_validator.py
- tests/models/xapi/test_base.py
- tests/models/xapi/test_navigation.py
- tests/models/xapi/test_video.py
The model rules constraint limited the validation & conversion logic to work only with disjoint rule sets, thus avoiding the case where a matching ruleset could lead to multiple results.
In the future, we intend to support xAPI profile validation.
However, xAPI profile template selection constraints are not always disjoint rulesets.
> 🔥(models) remove ModelRules constraint

- CHANGELOG.md
- setup.cfg
- src/ralph/api/__init__.py
- src/ralph/cli.py
- tests/test_dependencies.py
Current project dependencies definition needs more love:
1. if we want the project to be used as a library, we need to increase the primary dependencies version contraints, and,
2. when Ralph is installed as a library, the `ralph` command is installed and available in the PATH even if Click is not installed leading to unobvious error message when executing the aforementioned command. More than that, if installed as a CLI, the `runserver` command will fail if the the LRS flavor is not installed.
> Improve dependencies management

- tests/fixtures/hypothesis_configuration.py
- tests/fixtures/hypothesis_strategies.py
The new version of `hypothesis` emits a warning during boolean comparison of a hypothesis strategy which pollutes test logs.
Also, the new version of `pydantic` includes our fix for resolving nested JSON fields. thus we don't need our custom JSON resolver anymore.
> ✅(tests) fix hypothesis warnings

- CHANGELOG.md
- setup.cfg
- src/ralph/__init__.py
- src/tray/tray.yml
- EdX to xAPI converters for video events
- Improve Ralph's library integration by unpinning dependencies (and prefer ranges)
- Upgrade `fastapi` to `0.87.0`
> 🔖(minor) bump release to 3.1.0

- CHANGELOG.md
- src/tray/templates/services/app/deploy.yml.j2
When using the Elasticsearch (ES) backend in an LRS context, for SSL connections to the cluster, python's ES client requires access to the ES cluster self-generated CA root certificate.
> 🔧(tray) add CA cert file path for the LRS ES backend

- CHANGELOG.md
- setup.cfg
- src/ralph/__main__.py
- src/ralph/api/__init__.py
- src/ralph/conf.py
Sentry integration is too basic and requires to be a bit more configurable and adapted to used web framework (FastAPI).
We now install the FastAPI sentry integration to better track server performance and post mortem report.
Traces sample rate is now configurable for the CLI and the LRS.
> 🔧(project) improve Sentry integration

- CHANGELOG.md
- docs/api.md
- setup.cfg
- src/ralph/api/auth.py
- src/ralph/cli.py
- tests/api/test_auth.py
- tests/test_cli.py
Generating credentials to authenticate to our LRS should be smooth and painless for our users.
> ✨(cli) add the new "auth" command

- CHANGELOG.md
- README.md
- docs/index.md
Handbook with best practices and recommendations for contributors is now under https://handbook.openfun.fr instead of https://openfun.gitbooks.io/handbook/content
> 📝(project) update handbook link

- CHANGELOG.md
- setup.cfg
- src/ralph/cli.py
It's often useful to be able to quickly check version number of installed Ralph instance.
During this work, I also improved the following:
> CLI: add --version option

- Dockerfile
Fixes https://github.com/openfun/ralph/issues/246 which occurs on M1 Macs during `make bootstrap`.
Add the missing dependencies only for the `linux/arm64` target platform.
> :bug: Fix M1 Mac `make bootstrap` failures

- CHANGELOG.md
- setup.cfg
- src/ralph/__init__.py
- src/tray/tray.yml
- Add a new `auth` subcommand to generate required credentials file for the LRS
- Add an official Helm Chart (experimental)
- Implement support for AWS S3 storage backend
- Add CLI `--version` option
- Upgrade `fastapi` to `0.89.1`
- Upgrade `httpx` to `0.23.3`
- Upgrade `sentry_sdk` to `1.13.0`
- Upgrade `uvicorn` to `0.20.0`
- Tray: add the `ca_certs` path for the ES backend client option (LRS)
- Improve Sentry integration for the LRS
- Update handbook link to `https://handbook.openfun.fr`
- Upgrade base python version to 3.11 for the development stack and Docker
image
- Restore ES and Mongo backends ability to use client options
> 🔖(minor) bump release to 3.2.0

- CHANGELOG.md
- setup.cfg
Relax required Python version for Ralph to be used as a library in older Python environment (3.7+).
> 🧑‍💻(project) relax python version to 3.7

- CHANGELOG.md
- src/ralph/models/xapi/config.py
- src/ralph/models/xapi/fields/objects.py
- src/ralph/models/xapi/video/fields/contexts.py
- src/ralph/models/xapi/video/fields/results.py
Fix issue #254
After reading xAPI profile spec, Ralph should not forbid additional extensions.
Base models of Extension fields now allow extra fields.
> 🩹(xapi) allow extra fields for xAPI extensions

- CHANGELOG.md
- setup.cfg
- src/ralph/__init__.py
- src/tray/tray.yml
- Restored python 3.7+ support for library usage (models)
- Allow xAPI extra fields in `extensions` fields
> 🔖(minor) bump release to 3.3.0

- LICENSE.md
- mkdocs.yml
The GIP FUN-MOOC has been renamed France Université Numérique since few years now.
> 📝(docs) update copyright holder

- CHANGELOG.md
- src/ralph/api/__init__.py
When the SENTRY_DSN setting is active, the LRS server cannot start as the sentry_sdk module is not imported.
> 🐛(api) fix sentry integration

- CHANGELOG.md
- src/ralph/api/routers/statements.py
- tests/api/test_statements_get.py
- tests/api/test_statements_put.py
Make the statements endpoint more compliant with xAPI docs and samples.
- Add a PUT route for receiving a single statement to store
- Make trailing slashes on the `statements` endpoint optional
> ✨(api) add PUT route, make trailing slashes optional

- CHANGELOG.md
- arnold.yml
- setup.cfg
- src/helm/ralph/Chart.yaml
- src/ralph/__init__.py
- src/tray/tray.yml
- Implement PUT verb on statements endpoint
- Add ClickHouse database backend support
- Make trailing slashes optional on statements endpoint
- Upgrade `sentry_sdk` to `1.16.0`
> 🔖(minor) bump release to 3.5.0

- .circleci/config.yml
- Makefile
- README.md
- setup.cfg
- src/ralph/utils.py
FIXME statements is not properly checked in pylint when they are written in
docstrings.
- Add a step in the circle ci config for gint-lit job to detect presence of FIXME
statements.
- Remove remaining FIXME statements
- ➕ (bonus) Update name of `run` alias in Makefile
> Update fixme checking

- CHANGELOG.md
- src/ralph/backends/database/clickhouse.py
- tests/models/test_converter.py
In the current `clickhouse-connect` release (0.5.19) (see [CHANGELOG](https://github.com/ClickHouse/clickhouse-connect/blob/main/CHANGELOG.md#bug-fixes)), the quoting and escaping of array literals in server parameters is handled internally. Thus, we do not need to add quotes on our side.
> 👽️(backends) fix double quoting in ClickHouse backend server parameters

- CHANGELOG.md
- src/ralph/backends/database/clickhouse.py
During Ralph startup, when ClickHouse was not running Ralph would fail to connect and hang, never recovering. This change allows Ralph to start even without ClickHouse running and connect whenever it can.
> 🐛(backends) fix startup hang when ClickHouse is down

- CHANGELOG.md
- arnold.yml
- setup.cfg
- src/helm/ralph/Chart.yaml
- src/ralph/__init__.py
- src/tray/tray.yml
- Upgrade `httpx` to `0.24.0`
- Upgrade `fastapi` to `0.95.1`
- Upgrade `sentry_sdk` to `1.19.1`
- Upgrade `uvicorn` to `0.21.1`
- An issue with starting Ralph in pre-built Docker containers
- Fix double quoting in ClickHouse backend server parameters
- An issue Ralph starting when ClickHouse is down
> 🔖(patch) bump release to 3.5.1

- CHANGELOG.md
- src/helm/ralph/templates/hpa.yaml
- src/tray/templates/services/app/cronjob_pipeline.yml.j2
The batch/v1beta1 API is deprecated since kubernets 1.21 and is removed
in version 1.25. We can upgrade the manifests to use the batch/v1 api now.
Also, the autoscaling/v2beta1 API is deprecated since kubernetes 1.23 and is
removed in version 1.25. We can upgrade the manifests to use the
autoscaling/v2 api now.
> ⬆️(tray) upgrade deprecated api in k8s manifests

- CHANGELOG.md
- src/ralph/api/routers/statements.py
- tests/api/test_statements_get.py
Following #315, making a second GET request to the `more` irl, or querying with a query parameter, was failing due to a missing `?` after the endpoint name.
> 🐛(api) fix `more` irl on second request

- CHANGELOG.md
- arnold.yml
- setup.cfg
- src/helm/ralph/Chart.yaml
- src/ralph/__init__.py
- src/tray/tray.yml
- Add the ability to ignore health check routes for Sentry transactions
- Upgrade `sentry_sdk` to `1.22.2`
- Upgrade `uvicorn` to `0.22.0`
- LRS `/statements` `GET` method returns a code 400 with certain parameters
as per the xAPI specification
- Use batch/v1 api in cronjob_pipeline manifest
- Use autoscaling/v2 in HorizontalPodAutoscaler manifest
- Fix the `more` IRL building in LRS `/statements` GET requests
> 🔖(minor) bump release to 3.6.0

- CHANGELOG.md
- src/ralph/api/routers/statements.py
- src/ralph/backends/database/base.py
- src/ralph/backends/database/clickhouse.py
- src/ralph/backends/database/es.py
- src/ralph/backends/database/mongo.py
- tests/api/test_statements_get.py
The xAPI specification proposes identifying Agents using 4 methods (called [Inverse Functional Identifier](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#2423-inverse-functional-identifier)). Currently the API and backend only handle the `account` method (using `name` and `homePage`). 
Additionally, [the xAPI specification](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#213-get-statements) requires for the `GET /statements?agent=` endpoint to accept JSON (Agent or group of Agents) as a value for query parameter `agent`. Currently, this parameter accepts string and only filters on  `agent.account.name`.
The proposed change aims to allow querying for Agents (**groups of agents is still NOT handled**) following the specification.
> Add all Inverse Functional Identifier support for filtering by `agent`

- setup.cfg
Coverage was displaying correctly locally, but not on the CI test runs.
`src/ralph` path for pytest-cov works locally when Ralph is installed in editable mode, but does not work on the CI test runs where Ralph is installed in non editable mode (when the source files are under `site-packages/ralph`). A `ralph` path now covers both cases.
> 💚(circle) display test coverage in ci

- CHANGELOG.md
- Makefile
- docs/api.md
- src/ralph/api/__init__.py
- src/ralph/api/auth.py
- src/ralph/api/routers/statements.py
- src/ralph/backends/database/base.py
- src/ralph/backends/database/clickhouse.py
- src/ralph/backends/database/es.py
- src/ralph/backends/database/mongo.py
- src/ralph/cli.py
- tests/api/test_auth.py
- tests/api/test_statements_get.py
- tests/fixtures/auth.py
- tests/test_auth.py
- tests/test_cli.py
- tests/test_cli_usage.py
In link with #288 , we need a mechanism to assign an "Agent" ([in the sense of the xAPI specification](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#2421-when-the-actor-objecttype-is-agent)) to a user (to later be able to infer the "Authority" field when writing a statement). 
It was proposed  to add the "agent" representation as a field in the user credentials, which is what this PR implements. There is no contraint as to which of the 4 valid [IFI's](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#2423-inverse-functional-identifier) must be used.
Add "agent" to user credentials.
> 💥(cli) Add mandatory "agent" field to credentials

- .circleci/config.yml
- CHANGELOG.md
- Dockerfile
- docs/backends.md
- docs/index.md
- setup.cfg
- src/ralph/backends/database/clickhouse.py
- src/ralph/backends/http/__init__.py
- src/ralph/backends/http/base.py
- src/ralph/backends/http/lrs.py
- src/ralph/cli.py
- src/ralph/conf.py
- tests/backends/http/test_base.py
- tests/backends/http/test_lrs.py
- tests/fixtures/backends.py
- tests/test_cli_usage.py
In FUN perspective, we want to use our LRS in `warren` backend and intends to
make available `warren` for every one. Hence it should not directly depend on
the FUN made LRS. 
In the perspective of having a generic call to any LRS in data application, we
propose the implementation in the backends stack of `ralph` a new instance of
backend: the LRS one. It will allow anyone to be able to use any LRS in one's
application
Implementation to do list:
> Implement synchronous LRS backend

- .circleci/config.yml
- CHANGELOG.md
- arnold.yml
- setup.cfg
- src/helm/ralph/Chart.yaml
- src/ralph/__init__.py
- src/tray/tray.yml
- Implement synchronous `lrs` backend
- Implement xAPI virtual classroom pydantic models
- Allow to insert custom endpoint url for S3 service
- Cache the HTTP Basic auth credentials to improve API response time
- Support OpenID Connect authentication method
- Clean xAPI pydantic models naming convention
- Upgrade `fastapi` to `0.97.0`
- Upgrade `sentry_sdk` to `1.25.1`
- Set Clickhouse `client_options` to a dedicated Pydantic model
- Upgrade `httpx` to `0.24.1`
- Force a valid (JSON-formatted) IFI to be passed for the `/statements`
GET query `agent` filtering
- Upgrade `cachetools` to `5.3.1`
- `verb`.`display` field no longer mandatory in xAPI models and for converter
> 🔖(minor) bump release to 3.7.0

- CHANGELOG.md
- src/ralph/cli.py
- tests/test_cli_usage.py
When using the LRS backend to fetch statements with the CLI, it seems mandatory to be able to filter statements using a standard LRS query (`since`, `until`, `verb`, etc...).
> ⚡️(cli) allow to use a query for HTTP backends

- CHANGELOG.md
- arnold.yml
- setup.cfg
- src/helm/ralph/Chart.yaml
- src/ralph/__init__.py
- src/tray/tray.yml
- Implement edX open response assessment events pydantic models
- Implement edx peer instruction events pydantic models
- Implement xAPI VideoDownloaded pydantic model
(using xAPI TinCan `downloaded` verb)
- Allow to use a query for HTTP backends in the CLI
> 🔖(minor) bump release to 3.8.0

- src/ralph/backends/data/swift.py
- tests/backends/data/test_swift.py
- tests/conftest.py
- tests/fixtures/backends.py
Storage and Database backends had similar interfaces and usage, a new Data backend interface has been created.
With the `data` parameter changed to an Iterable, we cannot use high level SwiftService API to upload files anymore (it needs a file object source, not an iterable).
Changing to Connection lower-level API, which is more flexible.
> 🏗️(backends) unify data backends swift

- .circleci/config.yml
- Dockerfile
- setup.cfg
- src/ralph/backends/data/s3.py
- tests/backends/data/test_s3.py
- tests/conftest.py
- tests/fixtures/backends.py
Storage and Database backends had similar interfaces and usage, a new Data backend interface has been created.
Update S3 backend to follow new Data backend interface.
~~Add pydantic model for a history entry.~~ &rarr; moved to #317
> 🏗️(backends) unify data backends s3

- src/ralph/backends/data/clickhouse.py
- src/ralph/backends/lrs/base.py
- src/ralph/backends/lrs/clickhouse.py
- tests/backends/data/test_clickhouse.py
- tests/backends/lrs/test_clickhouse.py
- tests/conftest.py
- tests/fixtures/backends.py
Storage and Database backends had similar interfaces and usage, a new Data backend interface has been created.
Update Clickhouse backend to follow new Data backend interface.
Add pydantic model for a history entry.
> (backends) Unify data backends clickhouse

- CHANGELOG.md
- src/ralph/api/routers/statements.py
- tests/api/test_statements_get.py
As pointed out in https://github.com/openfun/ralph/issues/376 , validity of IRI (the expected input) when calling `GET /statements/?activty=` by `activity` is not currently being checked. This PR aims to correct this.
We enforce IRI check when querying by IRI. We return 422 Unprocessable Entity (the default for FastAPI), when input is not a valid IRI.
> (api) enforce valid IRI with `GET /statements/?activity=`

- CHANGELOG.md
- src/ralph/api/routers/statements.py
- src/ralph/backends/database/clickhouse.py
- src/ralph/backends/database/mongo.py
- tests/api/test_statements_post.py
- tests/api/test_statements_put.py
- tests/backends/database/test_mongo.py
Allow duplicate statements ids to pass without throwing errors if the statements are identical.
As discussed in #345 I've implemented changes to only throw 429 errors when the statements differ. This should allow bulk backfill of data or catching up statements lost due to operational errors to succeed in most cases.
A side effect of this refactor is that all backends should now have the same return structure from `query_statements_by_ids`. Previously they all differed slightly.
> ♻️(backends) change how duplicate statement ids are handled

- CHANGELOG.md
- setup.cfg
- src/helm/ralph/Chart.yaml
- src/ralph/__init__.py
- src/tray/tray.yml
- Upgrade `fastapi` to `0.100.0`
- Upgrade `sentry_sdk` to `1.28.1`
- Upgrade `uvicorn` to `0.23.0`
- Enforce valid IRI for `activity` parameter in `GET /statements`
- Change how duplicate xAPI statements are handled for `clickhouse` backend
General improvement for the Helm Chart:
- add dependencies for MongoDB and Clickhouse
- make persistence optional
- allow use existing PVC
- remove prefix label from ingress object name
- add missing namespace label
- make object name consistent
> 🔖(minor) bump release to 3.9.0

- setup.cfg
- tests/backends/data/test_ldp.py
We want to simplify our tests that are mocking the `request` package.
> ✅(tests) use requests_mock fixture in LDPDataBackend tests

- CHANGELOG.md
- Makefile
- docs/api.md
- src/ralph/api/__init__.py
- src/ralph/api/auth/basic.py
- src/ralph/api/auth/oidc.py
- src/ralph/api/auth/user.py
- src/ralph/api/routers/statements.py
- src/ralph/backends/database/base.py
- src/ralph/backends/database/clickhouse.py
- src/ralph/backends/database/es.py
- src/ralph/backends/database/mongo.py
- src/ralph/cli.py
- tests/api/auth/test_basic.py
- tests/api/auth/test_oidc.py
- tests/api/test_statements_get.py
- tests/fixtures/auth.py
- tests/test_cli.py
- tests/test_cli_usage.py
Rebasing and integrating the works on authentication:
- On one side was added:
- PR #342 💥(cli) add mandatory "agent" field to credentials
- PR #343 ✨(api) add "mine" option to fetch statements with matching authority
- On the other side was added the OpenIdConnect authentication method:
- PR #262 ✨(authentication) add OpenId Connect authentication
> (auth) Integration of "agent" field and "mine" query param with OpenIDConnect

- CHANGELOG.md
- README.md
- docs/contribute.md
- docs/index.md
- setup.cfg
- src/helm/ralph/values.yaml
- src/ralph/api/routers/statements.py
- src/ralph/backends/storage/fs.py
- src/ralph/backends/storage/ldp.py
- src/ralph/backends/storage/s3.py
- src/ralph/backends/storage/swift.py
- src/ralph/cli.py
- src/tray/vars/all/main.yml
- tests/backends/storage/test_ldp.py
- tests/backends/storage/test_s3.py
- tests/backends/storage/test_swift.py
- tests/test_cli.py
- tests/test_cli_usage.py
- tests/test_logger.py
As mentionned in #383 , cli currently uses `fetch` and `push`. This could be unified with the new terms `read` and `write`.
> (cli) Rename cli fetch & push to read & write

- docs/api.md
Parameters for adding an agent at credentials creation are:
- agent-ifi-mbox
- agent-ifi-mbox-sha1sum
- agent-ifi-openid
- agent-ifi-account
Adding the missing `ifi` and removing `name` and `homepage` for `account` type
in documentation.
> 📝(auth) fix user credentials creation documentation

- CHANGELOG.md
- src/ralph/api/forwarding.py
- src/ralph/api/routers/statements.py
- tests/api/test_forwarding.py
- tests/api/test_statements_get.py
- tests/api/test_statements_post.py
- tests/api/test_statements_put.py
As mentionned in https://github.com/openfun/ralph/issues/375 , invalid parameters passed to the LRS should prompt a 400 error code from the API (instead of 500 as is currently the case). This PR deals with this issue for GET, POST, and PUT.
Example: `/xAPI/statements?toto=2` should return 400.
The proposed solution would return 400 with the following message:
```
{
"detail": "The following parameter is not allowed: `toto`"
}
```
> (api) Return 400 status on invalid parameter in `/statements`

- CHANGELOG.md
- src/ralph/models/edx/converters/xapi/video.py
- src/ralph/models/xapi/video/contexts.py
- src/ralph/models/xapi/video/statements.py
- src/ralph/models/xapi/virtual_classroom/contexts.py
- tests/models/edx/converters/xapi/test_video.py
- tests/models/xapi/test_video.py
- tests/models/xapi/test_virtual_classroom.py
The latest version of the xapi video profile (1.0.3) seems to enforce the presence of a video profile activity in the
`context.contextActivities.category` field, which was previously validated to optionally contain the profile activity value.
> 🦺(models) make ProfileActivity presence mandatory

- CHANGELOG.md
- src/ralph/backends/http/lrs.py
- tests/backends/http/test_lrs.py
As described in https://github.com/openfun/ralph/issues/400 , the current `LRSHTTP` (which is derived from `AsyncLRSHTTP`) methods can't be called from within a running events loop (as is the case in warren). There is no obvious alternative (other than code duplication), as this pattern is not allowed by `asyncio`. As dicussed [here](https://discuss.python.org/t/calling-coroutines-from-sync-code-2/24093/19), it is also considered an anti pattern.
It has been decided to NOT change the code structure. Instead:
- if a method is called OUTSIDE of a running events loop (in a synchronous setting), the code still works as previously.
- if a method is called INSIDE of a running events loop (meaning the user is already working asynchronously), we raise an explicit error directing the user to …
> (api) disable lrshttp when called in events loop

- CHANGELOG.md
- src/tray/templates/services/app/cronjob_pipeline.yml.j2
- src/tray/templates/services/app/deploy.yml.j2
- src/tray/templates/volumes/history.yml.j2
- src/tray/vars/all/main.yml
Add the variable ralph_pvc_history_name in tray to allow to override the persistent volume name.
> 🔧(arnold) use var to allow override pvc name

- CHANGELOG.md
- src/ralph/backends/http/async_lrs.py
- src/ralph/backends/http/base.py
- tests/backends/http/test_async_lrs.py
- tests/backends/http/test_base.py
As suggested in https://github.com/openfun/ralph/issues/418 , it would be nice to introduce a limit to the number of statements that can be returned by `AsyncLRSHTTP.read()`. This PR implements this feature (with option named `max_statements`)
This is implemented by simply adding a break condition when looping on the statements generator.
> (backend) Add `max_statements` to read in LRSHTTP

- setup.cfg
- src/ralph/backends/data/async_es.py
- src/ralph/backends/data/async_mongo.py
- src/ralph/backends/data/base.py
- src/ralph/backends/data/clickhouse.py
- src/ralph/backends/data/es.py
- src/ralph/backends/data/fs.py
- src/ralph/backends/data/ldp.py
- src/ralph/backends/data/mongo.py
- src/ralph/backends/data/s3.py
- src/ralph/backends/data/swift.py
- tests/backends/data/test_async_es.py
- tests/backends/data/test_async_mongo.py
- tests/backends/data/test_base.py
- tests/backends/data/test_clickhouse.py
- tests/backends/data/test_es.py
- tests/backends/data/test_fs.py
- tests/backends/data/test_ldp.py
- tests/backends/data/test_mongo.py
- tests/backends/data/test_s3.py
- tests/backends/data/test_swift.py
- tests/backends/lrs/test_clickhouse.py
- tests/backends/lrs/test_es.py
- tests/backends/lrs/test_mongo.py
Synchronous backends such as Elasticsearch or Mongodb need their connection to
be close when finished.
> Add close method to synchronous backends

- CHANGELOG.md
- src/ralph/models/edx/converters/xapi/__init__.py
- src/ralph/models/edx/converters/xapi/enrollment.py
- tests/models/edx/converters/xapi/test_enrollment.py
`LMS` xAPI profile supports statements templates for course registration activities.
Enrollment events from Edx can be converted in xAPI
> Implement enrollments converters

- CHANGELOG.md
- src/ralph/api/routers/statements.py
- src/ralph/backends/database/base.py
- src/ralph/backends/database/clickhouse.py
- src/ralph/backends/database/es.py
- src/ralph/backends/database/mongo.py
- src/ralph/backends/http/async_lrs.py
- tests/backends/database/test_clickhouse.py
- tests/backends/database/test_es.py
- tests/backends/database/test_mongo.py
- tests/backends/http/test_async_lrs.py
Until now, LRS statement query parameter used in LRS backend was typed with a dictionary. However, the LRS specification defines a precise set of parameters. 
To query the statements resource with the LRS backend, a Pydantic model validates the input parameter according to the official LRS spec and the query parameters defined for `ralph` LRS API makes use of this model and extra parameters but without validation, as the usage is only for `ralph` and the data is trusted.
> Add LRS statement query parameter Pydantic model

- tests/api/test_statements_get.py
- tests/api/test_statements_post.py
- tests/api/test_statements_put.py
- tests/backends/http/test_async_lrs.py
- tests/fixtures/auth.py
- tests/helpers.py
- tests/test_helpers.py
The purpose of this PR is to make the tests more concise and readable.
It is proposed:
> 🎨(tests) clean tests by factoring statements and renaming

- README.md
As a new developper on Ralph, it is not obvious what commands are useful and where to find them. This commit (inspired by the [doc of OBC](https://github.com/openfun/open-badges-client#hack-on-the-project)) adds info on testing, linting, and updating dependancies to README in the contributing section.
> 📝(docs) add useful commands to "contributing" in README

- CHANGELOG.md
- src/helm/ralph/Chart.yaml
The version 23.x for clickhouse is the docker image version. 
The last major version for the clickhouse's helm chart is 4.
> 🐛(helm) fix clickhouse Helm's version

- CHANGELOG.md
- src/helm/ralph/templates/ingress.yaml
- src/helm/ralph/values.yaml
The PR #471 add the possibility to add more certificate to the Ralph's Ingress. But doesn't allow to use it.
This PR the delete Helm's values ``ingress.tls`` and ``ingress.hostname`` and create a new one.
``` yaml 
ingress:
hosts:
- domains:
- ralph.example.com
- ralph2.example.com
tls:
secretName: "ralph-example-com-tls" # This secret is a wildcard certificate for example.com
- domains:
- ralph.other-example.com
tls:
secretName: "ralph-other-example-com-tls"
```
Result
``` yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: release-name-ralph
labels:
helm.sh/chart: ralph-0.1.0
app.kubernetes.io/name: ralph
app.kubernetes.io/instance: release-name
app: ralph
service: app
app.kubernetes.io/version: "3.9.0"
app.kubernetes.io/managed-by: Helm
spec:
ingressClassName: ""
rules: …
```
> 🔧(helm) improve ingress's host management

- CHANGELOG.md
- docs/api.md
- setup.cfg
- src/ralph/api/auth/__init__.py
- src/ralph/api/auth/basic.py
- src/ralph/api/auth/oidc.py
- src/ralph/api/auth/user.py
- src/ralph/api/routers/statements.py
- src/ralph/conf.py
- tests/api/auth/test_basic.py
- tests/api/auth/test_oidc.py
- tests/api/test_statements_get.py
- tests/api/test_statements_post.py
- tests/api/test_statements_put.py
- tests/conftest.py
- tests/fixtures/auth.py
- tests/test_cli.py
- tests/test_conf.py
The current state of Ralph allows to restrict users by authority, but does not allow 1. An admin user 2. Finer access control (read, write). This PR aims to solve this issue by implementing `scopes` (a field already present in user accounts) which can allow restricted access.
The scopes proposed are a slight variation on the scopes defined by the [xAPI standard](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#details-15):
```
"statements/write",
"statements/read/mine",
"statements/read",
"state/write",
"state/read",
"define",
"profile/write",
"profile/read",
"all/read",
"all",
```
NB: This PR also proposes some cleaning (renaming tests and factorizing code in tests).
TODO:
> (api) Add option to enforce use of scopes (`all/read`, `all/write`, etc.)

- docker-compose.yml
- src/ralph/backends/data/async_es.py
- src/ralph/backends/http/async_lrs.py
- src/ralph/conf.py
- tests/api/test_forwarding.py
- tests/api/test_health.py
- tests/api/test_statements.py
- tests/api/test_statements_get.py
- tests/api/test_statements_post.py
- tests/api/test_statements_put.py
- tests/backends/http/test_async_lrs.py
- tests/conftest.py
- tests/fixtures/api.py
- tests/fixtures/backends.py
After backends unification and integration, we are not testing the API with
async_es and async_mongo.
Covering these backends highlighted some problems:
- limit of the `read` method of `async_es` backend was not correctly used
- `runserver` could not be used with `async_es` and `async_mongo`
- volume of elasticsearch docker compose service prevented reproducibility
- 🐛(backends) fix limit in `read` method of `async_es` backend
- ✨(api) add ability to use async backends for `runserver` command
- 🔧(projet) remove elasticsearch volume
- ✅(api) update tests to cover async backends
> Cover asynchronous backends in API tests

- .circleci/config.yml
- Dockerfile
- Makefile
- mkdocs.yml
- setup.cfg
Documentation under https://openfun.github.io/ralph/ lacks a version and is always following `master`, which can be confusing for the Ralph python package users.
> Setting up docs versioning

- Makefile
Missing backslash in Makefile leads to `-w` (write to disk) being ignored
when creating `auth.json`. This PR fixes this.
> 🐛(Makefile) add missing backslash

- tests/api/test_statements_get.py
One test seems to slow down the execution of our test set by 2 minutes **locally**
To reproduce:
`bin/pytest --durations=10 tests/api/`
```
============================================================================= slowest 10 durations ==============================================================================
60.52s call     tests/api/test_statements_get.py::test_api_statements_get_invalid_query_parameters[voidedStatementId]
60.23s call     tests/api/test_statements_get.py::test_api_statements_get_invalid_query_parameters[statementId]
3.37s call     tests/api/test_statements_post.py::test_api_statements_post_list_with_duplicate_of_existing_statement[get_clickhouse_test_backend]
3.11s call     tests/api/test_statements_post.py::test_api_statements_post_list_with_duplicate_of_existing …
```
> ✅(api) fix slow tests

- src/ralph/backends/lrs/base.py
- src/ralph/cli.py
- tests/backends/lrs/test_async_es.py
- tests/backends/lrs/test_async_mongo.py
- tests/backends/lrs/test_clickhouse.py
- tests/backends/lrs/test_es.py
- tests/backends/lrs/test_fs.py
- tests/backends/lrs/test_mongo.py
- tests/backends/test_utils_backends/valid_backends.py
Some pylint disables remain in the code, after we switched to Ruff.
Removing them.
> 🔥(project) remove remaining pylint warnings escapes

- src/ralph/backends/data/async_es.py
- src/ralph/backends/data/async_mongo.py
- src/ralph/backends/data/base.py
- src/ralph/backends/data/clickhouse.py
- src/ralph/backends/data/es.py
- src/ralph/backends/data/mongo.py
- tests/backends/data/test_async_es.py
- tests/backends/data/test_async_mongo.py
- tests/backends/data/test_clickhouse.py
- tests/backends/data/test_es.py
- tests/backends/data/test_fs.py
- tests/backends/data/test_ldp.py
- tests/backends/data/test_mongo.py
- tests/backends/data/test_s3.py
- tests/backends/data/test_swift.py
Data backends have two class attributes referring to pydantic model types that follow different naming conventions:
`settings_class` and `query_model`. 
For consistency, we propose to follow one naming convention.
> 🚚(backends) rename query_model to query_class

- pyproject.toml
Previously, pylint was checking if any `FIXME` or `TODO` was present in the
codebase.
Adding `FIX` (`flake8-fixme`) set of rules to Ruff to check these.
> 🔧(project) add flake8-fixme set of rules for Ruff

- tests/backends/data/test_async_es.py
- tests/backends/data/test_async_mongo.py
- tests/backends/data/test_clickhouse.py
- tests/backends/data/test_es.py
- tests/backends/data/test_fs.py
- tests/backends/data/test_ldp.py
- tests/backends/data/test_mongo.py
- tests/backends/data/test_s3.py
- tests/backends/data/test_swift.py
- tests/backends/http/test_async_lrs.py
- tests/backends/http/test_lrs.py
- tests/backends/lrs/test_async_es.py
- tests/backends/lrs/test_async_mongo.py
- tests/backends/lrs/test_clickhouse.py
- tests/backends/lrs/test_es.py
- tests/backends/lrs/test_fs.py
- tests/backends/lrs/test_mongo.py
- tests/backends/stream/test_ws.py
Having developed the unification of backends separately, this has led to a de-unification of test naming.
To align with the clean-up in the naming of API method tests, the names of backend tests have been shortened.
The suffix with the backend type(`data_backend`, `lrs_backend`) is unnecessary as the information is contained at the beginning of the test name.
> 🎨(tests) standardize naming for backend tests

- CHANGELOG.md
- src/ralph/api/routers/statements.py
- tests/api/test_statements_get.py
Adjusting response handling to return a more appropriate 422 HTTP exception
instead of a generic 500 error when the limit query parameter is strictly negative.
Use the arguments of the Query class. Set the greater or equal (`ge`) parameter's value to 0.
> ✅(api) enhance limit query parameter validation

- src/ralph/backends/data/async_es.py
- src/ralph/backends/data/async_mongo.py
- src/ralph/backends/data/base.py
- src/ralph/backends/data/clickhouse.py
- src/ralph/backends/data/es.py
- src/ralph/backends/data/fs.py
- src/ralph/backends/data/ldp.py
- src/ralph/backends/data/mongo.py
- src/ralph/backends/data/s3.py
- src/ralph/backends/data/swift.py
- src/ralph/backends/lrs/async_es.py
- src/ralph/backends/lrs/async_mongo.py
- src/ralph/backends/lrs/base.py
- src/ralph/backends/lrs/clickhouse.py
- src/ralph/backends/lrs/es.py
- src/ralph/backends/lrs/fs.py
- src/ralph/backends/lrs/mongo.py
- tests/backends/data/test_base.py
When data backends inherit from `BaseDataBackend`, they alter (specialize) the `__init__` and `read` method signatures with their proper `settings_class` and `query_class` types.
This is intended; however, this leaves a lot of freedom for data backend implementations - (for example, setting the type of `settings_class` to an `int`)
We propose to improve data backend typing using generic types.
> ✨(backends) generic data backends

- .circleci/config.yml
- CHANGELOG.md
- pyproject.toml
As a significant part of `ralph` no longer supports python3.7, it might be time to drop support for python3.7 officially.
> 💥(project) drop support for python3.7 and unpin dependencies

- CHANGELOG.md
- pyproject.toml
- src/ralph/backends/data/async_es.py
- src/ralph/backends/data/async_mongo.py
- src/ralph/backends/data/base.py
- src/ralph/backends/data/clickhouse.py
- src/ralph/backends/data/es.py
- src/ralph/backends/data/fs.py
- src/ralph/backends/data/ldp.py
- src/ralph/backends/data/mongo.py
- src/ralph/backends/data/s3.py
- src/ralph/backends/data/swift.py
- src/ralph/backends/http/async_lrs.py
- src/ralph/cli.py
- src/ralph/utils.py
- tests/backends/data/test_async_es.py
- tests/backends/data/test_async_mongo.py
- tests/backends/data/test_clickhouse.py
- tests/backends/data/test_es.py
- tests/backends/data/test_fs.py
- tests/backends/data/test_ldp.py
- tests/backends/data/test_mongo.py
- tests/backends/data/test_s3.py
- tests/backends/data/test_swift.py
- tests/backends/http/test_async_lrs.py
During data backend unification work, some shared utilities were developed to factorize duplication:
`parse_dict_to_bytes`, `read_raw` and `iter_by_batch`.
However, some backends still used their own implementation of these utilities, leading to some minor behavioral differences among backends.
~**Note:** This PR depends on #501~
> ♻️(backends) use common utilities among backends

- src/ralph/backends/data/async_es.py
- src/ralph/backends/data/async_mongo.py
- src/ralph/backends/data/base.py
- src/ralph/backends/data/clickhouse.py
- src/ralph/backends/data/es.py
- src/ralph/backends/data/fs.py
- src/ralph/backends/data/ldp.py
- src/ralph/backends/data/mixins.py
- src/ralph/backends/data/mongo.py
- src/ralph/backends/data/s3.py
- src/ralph/backends/data/swift.py
- src/ralph/backends/lrs/async_es.py
- src/ralph/backends/lrs/async_mongo.py
- src/ralph/backends/lrs/clickhouse.py
- src/ralph/backends/lrs/es.py
- src/ralph/backends/lrs/fs.py
- src/ralph/backends/lrs/mongo.py
- tests/api/test_statements_get.py
- tests/backends/data/test_async_es.py
- tests/backends/data/test_base.py
- tests/backends/data/test_es.py
- tests/backends/data/test_mixins.py
- tests/fixtures/backends.py
Currently, backends use a module-level logger instance for logging to allow filtering logs by backend.
However, when a backend inherits another backend, logs produced by the parent backend refer to the parent module (and not the current backend module).
**Note**: This PR depends on #510
> ♻️(backends) add logger property to data/lrs backends

- .circleci/config.yml
- CHANGELOG.md
- Dockerfile
- README.md
- docs/index.md
- pyproject.toml
Ralph package has a lot of extra dependencies, and it can be harsh having to list them when wanting to install a full package.
Adding three aliases:
- `backends` that groups all backends extra dependencies;
- `full` that groups all functional extra dependencies (`backends`, `cli` and `lrs`);
- `all` that groups all the extra dependencies (`full`, `ci` and `dev`).
> 🔧(project) add aliases for grouping extra dependencies

- src/ralph/backends/data/async_es.py
- src/ralph/backends/data/async_mongo.py
- src/ralph/backends/data/base.py
- src/ralph/backends/data/clickhouse.py
- src/ralph/backends/data/es.py
- src/ralph/backends/data/fs.py
- src/ralph/backends/data/ldp.py
- src/ralph/backends/data/mongo.py
- src/ralph/backends/data/s3.py
- src/ralph/backends/data/swift.py
- tests/backends/data/test_base.py
- tests/backends/data/test_clickhouse.py
- tests/backends/data/test_s3.py
- tests/backends/data/test_swift.py
Data backends that implement the `write` method repeatedly handle some common tasks (e.g., setting a default `chunk_size`).
We want to factorize those tasks.
We propose to use a template pattern to factorize repeated tasks.
We move core backend write implementation to private `_write_dicts` and `_write_bytes` methods and make the public `write` method perform common tasks and call the private methods.
**Note:** This PR depends on #515
> 🏗️(backends) use template method for write method in data backends

- src/ralph/backends/data/async_es.py
- src/ralph/backends/data/async_mongo.py
- src/ralph/backends/data/base.py
- src/ralph/backends/http/async_lrs.py
- tests/backends/data/test_async_es.py
- tests/backends/data/test_async_mongo.py
- tests/backends/data/test_base.py
- tests/backends/data/test_clickhouse.py
- tests/backends/data/test_es.py
- tests/backends/data/test_fs.py
- tests/backends/data/test_mongo.py
- tests/backends/data/test_s3.py
- tests/backends/data/test_swift.py
- tests/backends/http/test_async_lrs.py
We try to align the data backend interface with the http backends.
The `simultaneous` option allows the caller of an async data backend to write data concurrently.
**Note:** This PR depends on #519
Note: The current behavior of the `max_num_simultaneous` option differs slightly with the http backed implementation:
- We log a warning instead of raising an exception when  `max_num_simultaneous`  is set and `simultaneous` is `False`
- We do not accept unlimited concurrency when `max_num_simultaneous` is set to `None` - we default to the sequential behavior instead.
> ✨(backends) add simultaneous option for AsyncWritable data backends

- Makefile
- docker-compose.yml
Docker compose provides `healthcheck` since format version 3.4.
https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck
Changing from dockerize to docker healthchecks for all database services locally.
> 🔨(project) use docker healthcheck for database services

- src/ralph/backends/data/async_es.py
- src/ralph/backends/data/async_mongo.py
- src/ralph/backends/data/base.py
- src/ralph/backends/data/clickhouse.py
- src/ralph/backends/data/es.py
- src/ralph/backends/data/fs.py
- src/ralph/backends/data/ldp.py
- src/ralph/backends/data/mongo.py
- src/ralph/backends/data/s3.py
- src/ralph/backends/data/swift.py
- tests/backends/data/test_async_es.py
- tests/backends/data/test_async_mongo.py
- tests/backends/data/test_base.py
- tests/backends/data/test_s3.py
We try to align the data backend interface with the http backends.
The `greedy` option allows the caller to read all records greedily before the generator yields them.
**Note:** This PR depends on #520
Update: We propose to rename the greedy option to `prefetch: int` allowing us to set how many statements should be greedingly prefetched.
> ✨(backends) add greedy option for data backends

- .circleci/config.yml
We want to build and push `ralph-malph` package to PyPi for a pre-release.
We also want to build and push Ralph docker image for pre-release versions.
We should be able to do so when tagging appropriately (e.g. `4.0.0-b1`).
This prevents executing the other jobs triggered on tags that are:
- `deploy-docs`
- `release`
We also prevent tagging docker image `latest` for pre-releases.
> 💚(circle) prevent executing jobs for PyPi pre-release tags

- .circleci/config.yml
- .github/ISSUE_TEMPLATE/Support_question.md
- CHANGELOG.md
- Makefile
- README.md
- docs/contribute.md
- docs/index.md
- docs/theme/announce.html
- pyproject.toml
- src/helm/CHANGELOG.md
`master` naming for repos is deprecated in the tech industry.
`main` is now the popular choice, and it would be easier for devs that openfun default branches be named `main`.
- 🧑‍💻(project) prepare branch renaming from master to main
- 📝(project) rename `main` doc version to `dev`
> Prepare branch renaming to `main`

- CHANGELOG.md
- src/helm/CHANGELOG.md
- src/helm/ralph/Chart.yaml
- src/ralph/__init__.py
- src/tray/tray.yml
- Backends: Add `Writable` and `Listable` interfaces to distinguish supported
functionalities among `data` backends
- Backends: Add `max_statements` option to data backends `read` method
- Backends: Add `prefetch` option to async data backends `read` method
- Backends: Add `concurrency` option to async data backends `write` method
- Backends: Add `get_backends` function to automatically discover backends
for CLI and LRS usage
- Backends: Add client options for WSDataBackend
- Backends: Add `READ_CHUNK_SIZE` and `WRITE_CHUNK_SIZE` data backend settings
- Models: Implement Pydantic model for LRS Statements resource query parameters
- Models: Implement xAPI LMS Profile statements validation
- Models: Add `EdX` to `xAPI` converters for enrollment events
- Project: Add aliases for …
> 🔖(major) bump release to 4.0.0

- .circleci/config.yml
CircleCI is deprecating all ubuntu machines to ensure pipelines run on latest versions.
Changing ubuntu machines to `default` (latest stable version). Refer to https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177
> 💚(circle) change deprecated ubuntu machines

- docs/tutorials/helm.md
- docs/tutorials/lrs/index.md
- mkdocs.yml
- src/helm/README.md
Documentation is missing a tutorial/guide to deploy Ralph.
Making the Helm chart README general enough to be used both for a README and
for documentation.
> 📝(helm) add helm README tutorial to documentation

- .circleci/config.yml
- README.md
It would be nice to test Ralph Helm chart in CI, before pushing it to a registry.
> 👷(project) add jobs to build/test and push helm chart

- CHANGELOG.md
- UPGRADE.md
- src/helm/CHANGELOG.md
- src/helm/ralph/Chart.yaml
- src/ralph/__init__.py
- src/tray/tray.yml
- Add LRS multitenancy support for user-specific target storage
- `query_statements` and `query_statements_by_ids` methods can now take an
optional user-specific target
- Backends: switch LRSStatementsQuery since/until field types to iso 8601 string
- Removed `event_table_name` attribute of the ClickHouse data backend
> 🔖(minor) bump release to 4.1.0

- CHANGELOG.md
- pyproject.toml
- src/ralph/backends/loader.py
- src/ralph/conf.py
- tests/backends/test_loader.py
- tests/backends/test_utils_backends/valid_backends.py
The automatic backend discovery by package name implemented in the `get_backends` method allowed the use of namespace package plugins, which is undesired. We want to support backend discovery using package metadata (entry points) exclusively in the future.
P.S.: I haven't noticed a change in performance with the addition of entry point backend discovery:
Tried: `perf stat -r 10 ./bin/ralph read` (which loads all backends to display the help page):
- main (2.6699 +- 0.0402 seconds time elapsed)
- this PR (2.7070 +- 0.0624 seconds time elapsed)
> 🐛(backends) disallow namespace package discovery

- CHANGELOG.md
- src/ralph/backends/lrs/clickhouse.py
- src/ralph/backends/lrs/es.py
- src/ralph/backends/lrs/mongo.py
- tests/backends/lrs/test_async_es.py
- tests/backends/lrs/test_async_mongo.py
- tests/backends/lrs/test_clickhouse.py
- tests/backends/lrs/test_es.py
- tests/backends/lrs/test_fs.py
- tests/backends/lrs/test_mongo.py
- tests/helpers.py
In xAPI version 1.0.3, the presence of `objectType` is optional, defaulting to `Activity` when not specified.
When querying activities, the LRS should exclusively search for `object.id` rather than first filtering on objects with type `Activity`.
This concerns all LRS backends.
> 🐛(api) fix activity querying for statements with object missing a type

- CHANGELOG.md
- src/helm/CHANGELOG.md
- src/helm/ralph/Chart.yaml
- src/ralph/__init__.py
- src/tray/tray.yml
- Models: Add Edx teams-related events support
- Models: Add Edx notes events support
- Models: Add Edx certificate events support
- Models: Add Edx bookmark (renamed Course Resource) events support
- Models: Add Edx poll and survey events support
- Models: Add Edx Course Content Completion events support
- Models: Add Edx drag and drop events support
- Models: Add Edx cohort events support
- Models: Add Edx content library interaction events support
- Backends: Add `ralph.backends.data` and `ralph.backends.lrs` entry points
to discover backends from plugins.
- Backends: the first argument of the `get_backends` method now requires a list
of `EntryPoints`, each pointing to a backend class, instead of a tuple of
packages containing backends.
- API: The `RUNSERVER_BACKEND` configuration …
> 🔖(minor) bump release to 4.2.0

- docker-compose.yml
The warning `WARN[0000] docker-compose.yml: `version` is obsolete` is displayed.
The `version` is deprecated and not used anymore by the latest Compose file format 1.27.0+.
Removing the field.
_Note_: A discussion about it here https://github.com/openfun/joanie/pull/721/files#r1547736981
> 🔥(project) remove obsolete docker compose version

- .circleci/config.yml
In the `test-helm` job, we were building Ralph current image but were installing the helm chart without specifying an image tag. When not specified, Helm installs the `appVersion` of the image, fetching it from DockerHub repository and not testing the current build of the image.
Changing it so that the job tests the current build of the image for non-tagged workflows, but also tests that the `appVersion` has correctly been filled in for `-helm` tagged workflows.
> 💚(circle) test helm with ralph build image

- CHANGELOG.md
- src/ralph/backends/data/async_lrs.py
- src/ralph/backends/data/lrs.py
- src/ralph/conf.py
- tests/api/auth/test_oidc.py
- tests/backends/data/test_async_lrs.py
- tests/backends/data/test_async_ws.py
- tests/fixtures/backends.py
- tests/test_conf.py
Replace soon-to-be-deprecated `parse_obj_as` with `TypeAdapter` after Pydantic V2 migration.
Closes #551
> 👽️(project) replace deprecated `parse_obj_as`

- .gitignore
- renovate.json
Pydantic V2 is now supported by ralph. Temporarily, pydantic was a dependency
ignored for renovate to avoid automatic upgrades on its weekly tasks.
Tests for Pydantic are now made with polyfactory. Hypothesis ignored dependency
is removed too and its mention in gitignore.
- Remove pydantic and hypothesis in ignored dependencies of renovate
- Remove .hypothesis in .gitignore.
> 🔧(dependencies) update ignored dependencies in renovate configuration

- src/ralph/api/routers/statements.py
As FastAPI recommends in its documentation (https://fastapi.tiangolo.com/tutorial/query-params-str-validations/), it is preferable to use Annotated with Query instead of a Query default value.
On a side note, issue https://github.com/openfun/ralph/issues/556 is still open, as FastAPI does not yet allow to use custom objects as query parameters type (see https://github.com/tiangolo/fastapi/issues/10259).
> 🎨(api) use Annotated instead of Query as the default value

- src/ralph/models/xapi/concepts/activity_types/acrossx_profile.py
- src/ralph/models/xapi/concepts/activity_types/activity_streams_vocabulary.py
- src/ralph/models/xapi/concepts/activity_types/audio.py
- src/ralph/models/xapi/concepts/activity_types/tincan_vocabulary.py
Some activity types declared with Pydantic were missing default values for types
field which forces library users to declare the type value when model is
instantiated.
However, as these values are constants in xAPI semantics, we do
not want to request this from lib users.
> ♻️(models) set missing default values for xAPI activity types

- src/ralph/models/xapi/base/agents.py
- tests/api/auth/test_basic.py
- tests/api/auth/test_oidc.py
- tests/api/test_statements_post.py
- tests/api/test_statements_put.py
- tests/models/edx/converters/xapi/test_enrollment.py
- tests/models/edx/converters/xapi/test_navigational.py
- tests/models/edx/converters/xapi/test_server.py
- tests/models/edx/converters/xapi/test_video.py
- tests/models/xapi/base/test_agents.py
Until now, "Agent" object type was set to None as default value. When using
ralph xapi models to generate statements instances, objectType Agent is
generated with None value which is not the required behavior. 
We keep this field as optional in Pydantic model for validation and force
"Agent" value as a default value.
> ♻️(models) change default value "Agent" object type

- CHANGELOG.md
- UPGRADE.md
- docs/theme/announce.html
- src/helm/ralph/Chart.yaml
- src/ralph/__init__.py
- src/tray/tray.yml
- Models: Add Webinar xAPI activity type
- Upgrade `pydantic` to `2.7.0`
- Migrate model tests from hypothesis strategies to polyfactory
- Replace soon-to-be deprecated `parse_obj_as` with `TypeAdapter`
> 🔖(major) bump release to 5.0.0

- renovate.json
Renovatebot can automatically upgrade images used in `Dockerfile`,
`docker-compose` and `circleci` configuration.
To avoid upgrade manually packages when developers have noticed an image has
been freshly released, we set the automatic upgrades on Ralph, for a first test.
> 🔧(project) add docker and ci managers in renovatebot configuration

- CHANGELOG.md
- src/ralph/api/models.py
- tests/api/test_models.py
Some statement with an object id  consisting of an url with https scheme and a
port were altered during validation, losing the port.
Since ids should remain unchanged, we now ensure that validation preserves the
ids by validating only against the string type.
> 🐛(api) fix LaxStatement validation to prevent IDs modification

- CHANGELOG.md
- src/helm/CHANGELOG.md
- src/helm/ralph/Chart.yaml
- src/ralph/__init__.py
- src/tray/tray.yml
- Force Elasticsearch REFRESH_AFTER_WRITE setting to be a string
- Fix LaxStatement validation to prevent statements IDs modification
> 🔖(patch) bump release to 5.0.1

- CHANGELOG.md
- src/ralph/models/xapi/base/results.py
The scaled field in result.score was incorrectly set as an integer. According to xAPI documentation, it should be a decimal (ranging from -1 to 1).
Closes #612
> 🐛(models) fix statement.result.score.scaled type

- pyproject.toml
The CI is failing on tests over the LDP backend.
The OVH Python dependency was previously set to a minimum version of 1.0.0, which left Ralph vulnerable to breaking changes in the LDP backend.
Pinning to version 1.1.0 as the 1.2.0 requires additional integration.
> 📌(project) pin ovh dependency to 1.1.0

- .circleci/config.yml
- docker-compose.yml
- Release workflow was triggered on tags and on changes on the `main` branch. Changing it so it is triggered only on tags.
- Clickhouse is stuck unhealthy as localhost is not accessible in the container anymore. Fixing it by pinging `0.0.0.0` instead.
> 💚(circle) trigger release only on tags
